### ISSUE TITLE
user not found

### ISSUE THREAD

**Issue by aeonSolutions** [ChappIO/git-backup#25]
Hi there,
i've setup a config file and when i run git-backup i get the error message below:

D:\GitHub> git-backup-windows-x64
2024/08/22 09:29:38 inscure: false
2024/08/22 09:29:38 === github.com ===
2024/08/22 09:29:39 Failed to verify connection to job [github.com]: GET https://api.github.com/api/v3/user: 404 Not Found []

i did a quick code review of the github.go file
line 51: 		gitUrl.User = url.UserPassword("github", c.AccessToken)

it looks like you need to add another variable to the config file to add the username email

**Comment by ChappIO** [comment]
Hi, what did you enter in your configuration file at `github[0].access_token`? If that's a proper access token, the username should not be required.

You can generate an access token from your profile: https://github.com/settings/tokens/new?scopes=repo,read:org
