### ISSUE TITLE
Q: Does this retain history as well?

### ISSUE THREAD

**Issue by shivam-baghla** [ChappIO/git-backup#26]
Just the question

**Comment by ChappIO** [comment]
Yes, absolutely. This tool will use git to clone each discovered repository. So this means you'll find every repository in your account checked out at in the backups target folder. As if you checked them out yourself.

**Comment by Herve-M** [comment]
Is it a bare clone or normal clone?

**Comment by ChappIO** [comment]
@Herve-M by default this is a normal clone. But if you want to save space you can [create a bare clone instead](https://github.com/ChappIO/git-backup?tab=readme-ov-file#usage-cli).
